Диплом.stat_svc before review
KukushkinIgorA/java-explore-with-me pull request #3
Opened 2023-03-17 06:30 UTC by KukushkinIgorA

2023-03-17 20:13 UTC, EvgenyKoptubenko commented on stats-server/stats-service/src/main/java/ru/practicum/explorewithme/stats/model/Hit.java
> +@EqualsAndHashCode
EqualsAndHashCode не должно быть в Entity

2023-03-17 20:14 UTC, EvgenyKoptubenko requested changes
Работа сделана хорошо. Есть замечание по EqualsHashCode в Entity

2023-03-19 11:12 UTC, KukushkinIgorA commented
> Работа сделана хорошо. Есть замечание по EqualsHashCode в Entity

Убрал

2023-03-19 19:50 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Спасибо.

2023-03-20 08:49 UTC, merged